name: CI FastAPI

on:

  pull_request:


env:
  python_version: 3.9
  # Variables used to configure
  IMAGE_REGISTRY: ghcr.io
  IMAGE_REPO: jasilez/fastapi-lab
  VERSION: develop

jobs:

  pytest:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov pytest-html pytest-sugar pytest-json-report
        pytest -v --cov --html=reports/pytest/report.html
    - name: Archive pytest coverage results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-coverage-report
        path: reports/pytest/

  docker_ci:
    name: Build & Push Image
    needs: pytest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push into ghcr.io
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          load: false
          pull: false
          push: true # ${{ github.event_name == "pull_request" }}    
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}:latest
      
      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
